# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import ner_pb2 as ner__pb2


class NerStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.process = channel.unary_unary(
        '/ner.Ner/process',
        request_serializer=ner__pb2.NerRequest.SerializeToString,
        response_deserializer=ner__pb2.NerReply.FromString,
        )


class NerServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def process(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_NerServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'process': grpc.unary_unary_rpc_method_handler(
          servicer.process,
          request_deserializer=ner__pb2.NerRequest.FromString,
          response_serializer=ner__pb2.NerReply.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'ner.Ner', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
